### ISSUE TITLE
Image EXIF is uncorrected in api feed, though corrected on main site

### ISSUE THREAD

**Issue by dtipson** [mobilizeamerica/api#12]
Example:
https://events.mobilizeamerica.io/api/v1/organizations/183/events?per_page=200&zipcode=04654&max_dist=30

That result includes this raw image: https://mobilize-uploads-prod.s3.amazonaws.com/uploads/event/IMG_0556_20180911191015826801.JPG

Which when used in a browser like Chrome, gets rotated upside down because of it's EXIF rotation value.

On the mobilize site, it appears that the original image has been run through an image rendering proxy, which has corrects the EXIF problem (probably also by converting it to webp): https://events.mobilizeamerica.io/standupamerica/event/23978/

It would be ideal if api image results matched a cached version of those available on the site, including any EXIF correction.

**Comment by margotkriete** [comment]
@dtipson, thanks for filing this. It should be fixed now.
