### ISSUE TITLE
event id 107310 has null lat long

### ISSUE THREAD

**Issue by majestique** [mobilizeamerica/api#41]
https://www.mobilize.us/yang2020/event/107310/

```
"location":{  
            "venue":"",
            "address_lines":[  
               "131-04 Meridian Rd",
               ""
            ],
            "locality":"Queens",
            "region":"NY",
            "country":"US",
            "postal_code":"11368",
            "location":{  
               "latitude":null,
               "longitude":null
            },
```

**Comment by majestique** [comment]
This is due to address being an open field, it needs to be restricted to existing addresses only. Thus  making the data inconsistent. Please let us know if you're planning to fix this.

**Comment by kylehg** [comment]
Hey @majestique! Sorry to just respond to this, we don't monitor this repo for issues. Unfortunately lat/long can be null if geocoding fails for some reason, though we're always striving to reduce this.
