### ISSUE TITLE
Biden Organization

### ISSUE THREAD

**Issue by kailukowiak** [mobilizeamerica/api#67]
When I run: https://api.mobilize.us/v1/organizations I get a list of organizations but I can't see Joe's one: https://www.mobilize.us/joebiden/. 

I need this to find Joe's events to post on a volunteer slack.

Thanks.

**Comment by something-something-something** [comment]
It is 1393.

The easiest way to find it seems to be too look at an event that you know is run by the organization and look at the sponsor field for the id of the organization.

**Comment by kailukowiak** [comment]
Thank you so much. I was able to find it once I looped over multiple pages.

Thanks for your work!
Kai

___________
Kai Samuel Lukowiak
