### ISSUE TITLE
List Organization Events returning events with null fields

### ISSUE THREAD

**Issue by zcollins0** [mobilizeamerica/api#69]
I've noticed that recently (within the last week or so?) the List Organization Events API has started returning events that contain timeslots, but every field on the event and timeslot is null except for the timeslot start and end dates. Prior to this, I noticed that some events were not accessible through the browser - going to the event URL would give me a message that the event has been deleted - but they were still returned in the list organization events API. I'm not sure if that's related.

I know that I'm not hitting the limit of 1000 results - the count in the events object is 408 (as of writing this issue), and I've confirmed that the limit is 1000.

Organization ID 1255, if it helps.

Here's an example:

```
{'featured_image_url': None, 'contact': None, 'browser_url': None, 'tags': None, 'created_by_volunteer_host': False, 'timezone': 'America/New_York', 'title': None, 'high_priority': False, 'accessibility_notes': None, 'is_virtual': True, 'address_visibility': 'PUBLIC', 'sponsor': None, 'created_date': None, 'timeslots': [
        {'start_date': 1586232000, 'id': None, 'end_date': 1586318340, 'is_full': False
        },
        {'start_date': 1586318400, 'id': None, 'end_date': 1586404740, 'is_full': False
        },
        {'start_date': 1586404800, 'id': None, 'end_date': 1586491140, 'is_full': False
        },
...
```

**Comment by kylehg** [comment]
This should now be fixed!
