### ISSUE TITLE
The query string in [next] looks strange

### ISSUE THREAD

**Issue by MikeiLL** [mobilizeamerica/api#73]
Hi Kyle and crew.

I'm wondering about some of the attributes in the returned `[next]` (and `[previous]`) attributes:

```
[next] => https://api.mobilize.us/v1/organizations?amp=&organization_id=1&page=3&per_page=15
```

Is the `amp=` expected, or am I doing something wrong somewhere? Thanks.

**Comment by kylehg** [comment]
Hey @MikeiLL, it might be something weird happening on your end? Our `next` and `prev` params somewhat naively echo the current query params back, just with the page + per_page modified. So if `amp` got introduced for some reason it'll stay there, but if you start with a well-formed URL like https://api.mobilize.us/v1/organizations?organization_id=1 the params should remain normal.

**Comment by MikeiLL** [comment]
> Hey @MikeiLL, it might be something weird happening on your end? Our `next` and `prev` params somewhat naively echo the current query params back, just with the page + per_page modified. So if `amp` got introduced for some reason it'll stay there, but if you start with a well-formed URL like https://api.mobilize.us/v1/organizations?organization_id=1 the params should remain normal.

Thanks, Kyle.
