### ISSUE TITLE
How do you find your organization ID?

### ISSUE THREAD

**Issue by emschwartz** [mobilizeamerica/api#74]
I may be missing something obvious but is there a way to find your organization ID aside from paging through the list of all organizations to find the one that matches the organization's name?

**Comment by kylehg** [comment]
Hey @emschwartz ! We used to surface this ID for your organization in the dashboard settings page, but it seems to have gone away... we'll look into where it went! 

In the meantime, as a hack you can go to most organization pages, view the console, and see a log line with "Loaded embedded data" that includes a `current_organization` object. That will have the ID.

**Comment by kylehg** [comment]
Ok, the org ID should be back in the settings page tomorrow!

**Comment by emschwartz** [comment]
Hey @kylehg :wave: 

Thanks!

**Comment by misainiossh** [comment]
@kylehg is it gone again?

**Comment by arfin** [comment]
Hey @islamtg! You're commenting on a past issue with the Mobilize API, but posted a link to the Github API. Which are you looking to use?

If you're indeed trying to use the Mobilize API:
1. Your organization ID should still be visible in your dashboard. It's at the top of mobilize.us/dashboard/<your_org_slug>/settings/
2. Our API does indeed use /organizations. You can find the documentation here: https://github.com/mobilizeamerica/api

**Comment by arfin** [comment]
I think you are in the wrong place. This ticket is for the Mobilize API. We're consumers of github, and cannot help with using github. You might want to try https://github.community/ or https://support.github.com/contact

**Comment by fatihthedeveloper** [comment]
> Ok, the org ID should be back in the settings page tomorrow!

@kylehg can you show me a screenshot of where it's supposed to be? Thx

**Comment by natezmatthews** [comment]
Hi @fatihthedeveloper, we have not been keeping on top of these issues pages, but if you get in contact with our support team they will be able to help you: https://help.mobilize.us/en/articles/1915954-contact-mobilize-support
Thanks.
