### ISSUE TITLE
What is more up-to-date? This or mobilize.readme.io?

### ISSUE THREAD

**Issue by alxrsngrtn** [mobilizeamerica/api#80]
I notice differences in the API specified in this repo and established here: https://mobilize.readme.io/

What's is the source-of-truth?

**Comment by ramillim** [comment]
@alxrsngrtn the doc you linked is for https://www.mobilize.io/ a community management platform that is not related to us. This repository is the only API documentation for volunteer management platform https://mobilize.us/

**Comment by alxrsngrtn** [comment]
Ah! Thanks for sorting that out for me. Sorry for the confusion.
